### ISSUE TITLE
Inspired

### ISSUE THREAD

**Issue by tznind** [Ion-manden/firestore-cli#2]
Hey just wanted to say thankyou for creating this and for the [help getting it connected to emulator](https://github.com/Ion-manden/firestore-cli/issues/1).

I realized that I needed sub collection support at work so as a hobby I decided to create a port of this in Terminal.Gui (c#).

[I've credited you over at the repo](https://github.com/tznind/nfirestore-cli) which I've called `nfirestore-cli`.

But thought you  might get a kick out of seeing it:

![firestore-tui2](https://github.com/tznind/nfirestore-cli/assets/31306100/e34902c2-0830-4f63-959c-64171142c7bf)

**Comment by Ion-manden** [comment]
Awesome! Have linked to it in the readme, maybe someone else needs to work with sub collections.
